[boom_or_bubble]
title = "AI Boom/Bubble Monitor newsfeed"
url = "https://boomorbubble.ai/news"
entrySelector = ":root"
#entrySelector = "tbody tr"
titleSelector = "*"
linkSelector = "*"
waitUntil = "load"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ":root"
#entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
