[boom_or_bubble]
title = "AI Boom/Bubble Monitor newsfeed"
url = "https://boomorbubble.ai/news"
entrySelector = ":root"
titleSelector = "tbody tr td:nth-of-type(4)"
linkSelector = "tbody tr a"
waitUntil = "load"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
