[boom_or_bubble]
title = "AI Boom Bubble Monitor newsfeed"
url = "https://boomorbubble.ai/news"
#entrySelector = ":root"
waitForSelector = "tbody"
entrySelector = "tbody tr"
titleSelector = "td:nth-of-type(4)"
linkSelector = "a"
waitUntil = "load"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
#entrySelector = ":root"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
waitUntil = "load"
