# get loaded page contents
# entrySelector = ":root"

# entry for debugging
[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
waitUntil = "load"

[boom_or_bubble]
title = "AI Boom Bubble Monitor newsfeed"
url = "https://boomorbubble.ai/news"
waitForSelector = "tbody"
entrySelector = "tbody tr"
titleSelector = "td:nth-of-type(4)"
linkSelector = "a:not([href*=' ']"
waitUntil = "load"
