# get loaded page contents
# entrySelector = ":root"

# entry for debugging
[wiki_fun_facts]
title = "Wikipedia â€” did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"
waitUntil = "load"

[boom_or_bubble]
title = "AI Boom Bubble Monitor newsfeed"
url = "https://boomorbubble.ai/news"
waitForSelector = "tbody"
entrySelector = "tbody tr"
titleSelector = "td:nth-of-type(4)"
linkSelector = "a:not([href*=' '])"
waitUntil = "load"
