name: Publish RSS feeds to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 5:30 and 17:30:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

env:
  CI: true
jobs:
  publish-feeds:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps firefox
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      - run: npm install -g tsx
      # - run: npx playwright install --with-deps firefox
      - name: Clone feed-me-up-scotty (customizations branch)
        run: |
          git clone --depth 1 --branch customizations https://github.com/std-move/feed-me-up-scotty.git ./feed-me-up-scotty
          cd feed-me-up-scotty
          npm install --legacy-peer-deps
          npm run build   # outputs JS to dist/
      - name: Run feed-me-up-scotty
        run: DEBUG="info" npx ./feed-me-up-scotty
      - name: Deploy to GitHub Pages
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote add gh-pages-remote https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git fetch --no-recurse-submodules
          git worktree add ./gh-pages gh-pages
          cd gh-pages
          git rm -r .
          cp -r ../public/. .
          git add .
          git commit --message="Deploying to GitHub Pages from $GITHUB_SHA"
          git push gh-pages-remote gh-pages:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
